# Generated by Django 3.1.6 on 2021-09-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_office_name', models.CharField(max_length=200, unique=True)),
                ('branch_office_address', models.CharField(blank=True, max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('images', models.ImageField(upload_to='photos/branchoffice')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
