# Generated by Django 3.1.6 on 2021-09-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutioncategory', '0002_auto_20210924_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
