# Generated by Django 3.1.6 on 2021-09-24 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solutioncategory', '0003_auto_20210924_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('small_service_description', models.TextField(blank=True, max_length=500)),
                ('service_description', models.TextField(blank=True, max_length=500)),
                ('price', models.FloatField()),
                ('is_available', models.BooleanField(default=True)),
                ('images', models.ImageField(upload_to='photos/service')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutioncategory.category')),
            ],
        ),
    ]
